spring: # Spring config
    config: # config
        activate: # activate
            on-profile: prod # on which profile (service run mode) this configuration should be loaded

    datasource:
        url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/transaction
        username: ${DB_USER:postgres}
        password: ${DB_PASSWORD:postgres}
        hikari:
            maximum-pool-size: ${DB_POOL_SIZE:50}

    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: false

logging: # logging configuration (overrides logback logging levels)
    level: # levels
        root: INFO # default logging level for all unspecified loggers
        com.neo.tx: INFO # minimum level for the application package (log.info(), log.debug(), etc)
        com.fasterxml.jackson: INFO # Jackson logs (JSON serialization/deserialization)
        liquibase: INFO # Liquibase migration logs
        org.hibernate.SQL: INFO # Hibernate SQL statement logging (prints SQL queries)
        org.hibernate.orm.jdbc.bind: TRACE # Hibernate parameter binding logger (shows bound values with TRACE)
        org.springframework.web: INFO # Spring Web / MVC logs
        org.springframework.web.servlet.DispatcherServlet: INFO # Specific logger for DispatcherServlet (main Spring MVC dispatcher. INFO prints request lifecycle messages)

properties: