spring: # Spring config
  config: # config
    activate: # activate
      on-profile: dev # on which profile (service run mode) this configuration should be loaded

  datasource:
    url: jdbc:postgresql://localhost:5432/transaction
    username: marshmallow
    password: tasty

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: WARN
    com.neo.tx: WARN
    com.fasterxml.jackson: WARN
    liquibase: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.springframework.web: WARN
    org.springframework.web.servlet.DispatcherServlet: WARN

  file:
    name: ./logs/service.log # log file path