spring: # Spring config
  config: # config
    activate: # activate
      on-profile: dev # on which profile (service run mode) this configuration should be loaded

  datasource:
    url: jdbc:postgresql://localhost:5432/transaction
    username: marshmallow
    password: tasty

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    root: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: ./logs/service.log # log file path